# =============================================================================================
# = DATA SOURCE
# =============================================================================================
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# =============================================================================================
# = SERVICE
# =============================================================================================
service:
  properties:
    short-code: STR
  user:
    one:
      name: Ishmum Jawad Khan
      email: ishmumkhan@gmail.com
      password: RandomPass1
    two:
      name: A Unique Person
      email: unique@mail.com
      password: RandomPass2
    three:
      name: Another Unique Person
      email: veryunique@mail.com
      password: RandomPass3
