# =============================================================================================
# = DATA SOURCE
# =============================================================================================
spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: omdb_test
  liquibase:
    default-schema: omdb_test
    drop-first: true
    contexts: test
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/omdb
    username: postgres
    password: postgres
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# =============================================================================================
# = SERVICE
# =============================================================================================
service:
  properties:
    short-code: STR